### ISSUE TITLE
Option to use generator to append existing node-js typescript projects

### ISSUE THREAD

**Issue by sandyklark** [EndemolShineGroup/generator-nodejs-ts#12]
## Description

A prompt at the start of the generator that allows a project to be updated instead of generated.

### What is the use case that should be solved?

This should do things like:
- get default **projectName** and **projectDescription** from `package.json`
- gracefully merge existing dependencies with template dependencies
- keep existing project structure intact

### If there is additional config how would it look?

An additional prompt at the start of the generator prompts that lets the user know an existing `package.json` has been detected, the user can then choose to `append`, `abort` or `overwrite`.

## Additional Data

***Version of `generator-nodejs-ts` you're using***:  1.1.0

***Node Version***: 8.11.4

***Operating System***:  osx 10.13

**Comment by hassankhan** [comment]
I'd recommend splitting the generator into subgenerators instead. An existing repo would likely already have Git initialised, so any changes should be visible to the committer.
