### ISSUE TITLE
Add src/ and coverage/ folders to .npmignore

### ISSUE THREAD

**Issue by hassankhan** [EndemolShineGroup/generator-nodejs-ts#15]
### What is the use case that should be solved?

We should keep our dependency's size as small as possible for consumers. This means removing code/assets that are unused - in our case this means the `src/` folder (since we compile code to `dist/`) and the `coverage/` folder (which is generated by Jest).

## Additional Data

***Version of `generator-nodejs-ts` you're using***: 1.1.0

***Node Version***: 8.10

***Operating System***: macOS 10.13

**Comment by sandyklark** [comment]
[.npmignore][ignore-link] already has the pattern `!generators/*`

[ignore-link]: https://github.com/EndemolShineGroup/generator-nodejs-ts/blob/0831760abd8e50bcbbb1f20a2eb6cf16b62a51a2/.npmignore#L1
